initStore([
  {
    id: 0,
    title: 'Cyberpunk 2077: Ultimate Edition (PS5/Xbox)',
    description: 'Open-World-Rollenspiel mit der Erweiterung Phantom Liberty inklusive.',
    price: 119.95,
    discountPrice: 99.95,
    image: 'img/service-1.jpg',
  },
  {
    id: 1,
    title: 'Grand Theft Auto V (PS5)',
    description: 'Enthält GTA V Story-Modus und GTA Online mit Verbesserungen für PS5.',
    price: 58.95,
    discountPrice: 29.95,
    image: 'img/service-2.jpg',
  },
  {
    id: 2,
    title: 'Cyberpunk 2077: Phantom Liberty (DLC)',
    description: 'Spannende Agenten-Erweiterung für Cyberpunk 2077.',
    price: 44.95,
    discountPrice: 33.71,
    image: 'img/service-3.jpg',
  },
  {
    id: 3,
    title: 'EA Sports FC 24 (PS5)',
    description: 'Neueste Fußballsimulation mit neuen Ligen und Spielmechaniken.',
    price: 99.95,
    discountPrice: 89.95,
    image: 'img/service-4.jpg',
  },
  {
    id: 4,
    title: 'Elden Ring (PS5/PC)',
    description: 'Kritisch gefeiertes Open-World-Rollenspiel von den Machern von Dark Souls.',
    price: 79.95,
    discountPrice: 59.95,
    image: 'img/service-5.jpg',
  },
  {
    id: 5,
    title: 'Mario Kart 8 Deluxe (Switch)',
    description: 'Die ultimative Version des beliebten Nintendo-Rennspiels.',
    price: 89.95,
    discountPrice: 74.95,
    image: 'img/service-6.jpg',
  },
]);
