initStore([
  {
    id: 0,
    title: 'Horizon Forbidden West (PS5/PS4)',
    description: 'Episches Open-World-Abenteuer mit atemberaubender Grafik und fesselnder Geschichte.',
    price: 69.95,
    discountPrice: 54.95,
    image: 'images/service-1.jpg',
  },
  {
    id: 1,
    title: 'Call of Duty: Modern Warfare II (PC/PS5/Xbox)',
    description: 'Intensive Shooter-Erfahrung mit packendem Multiplayer-Modus.',
    price: 79.95,
    discountPrice: 59.95,
    image: 'images/service-2.jpg',
  },
  {
    id: 2,
    title: 'The Legend of Zelda: Tears of the Kingdom (Switch)',
    description: 'Fortsetzung des legendären Abenteuers mit neuen Welten und Herausforderungen.',
    price: 69.95,
    discountPrice: 62.95,
    image: 'images/service-3.jpg',
  },
  {
    id: 3,
    title: 'FIFA 24 (PC/PS5/Xbox)',
    description: 'Neueste Fußballsimulation mit realistischen Spielerbewegungen und Ligen.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'images/service-4.jpg',
  },
  {
    id: 4,
    title: 'Resident Evil Village (PC/PS5/Xbox)',
    description: 'Gruseliger Survival-Horror mit spannender Story und intensiver Atmosphäre.',
    price: 39.95,
    discountPrice: 29.95,
    image: 'images/service-5.jpg',
  },
  {
    id: 5,
    title: 'Super Smash Bros. Ultimate (Switch)',
    description: 'Actionreicher Kampfspiel-Klassiker mit einer großen Auswahl an Charakteren.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'images/service-6.jpg',
  },
]);
